application: carcoop
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /index.js
  static_files: index.js
  upload: index.js

- url: /style.css
  static_files: style.css
  upload: style.css

- url: /test
  static_files: test/index.html
  upload: test/index.html

- url: /test
  static_dir: test

- url: /.*
  script: index.py
